config/routes.rb
Spotcandy::Application.routes.draw do
  resources :photos

  devise_for :admin

  resources :candies, :except => [:show]

  resources :venues, :except => [:show]
  

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  
  resources :users
  resources :admin, :only => [:index]
  
  get "candies/cleanup"
  get "candies/privileges"
  
  match 'auth/:provider' => 'authentications#index', :constraints => {:provider => /foursquare|facebook/}
  match 'auth/:provider/callback', :to => 'authentications#callback'
  match 'foursquare/connect' => 'authentications#connect'
  match 'search_candies' => "venues#search"
  match 'venue/:id/candies' => "venues#candies"
  match 'venue/people' => "venues#people"
  match 'venue/:id/add' => "venues#add"
  match 'venue/:id/watch' => "venues#watch"
  match 'venues/trending' => "venues#trending"
  match 'venues/popular' => "venues#popular"
  match 'venues/history' => "venues#history"
  match 'venues/random' => "venues#random"
  match 'candy/:id/add' => "users#add_candy"
  match 'candy/:id/remove' => "users#remove_candy"
  match 'candy/:id/flag' => "candies#flag"
  match 'candy/:id/update_profile' => "candies#update_profile"
  match 'candy/:id/photos' => "candies#detail"
  match 'candy/:id/display' => "candies#display"
  match 'candy/:pid/profile' => "candies#profile"
  match 'candies/cleanup' => "candies#cleanup"
  match 'candies/:id' => "candies#show"
  match 'candies-grid' => "candies#grid"
  match 'user/:id/candies' => "users#candies"
  match 'scout/:id/candies' => "users#candies_list"
  match 'leaderboard' => "pages#home"
  match 'faq' => "pages#faq"
  match 'spotted' => "pages#stream"
  match 'pages/test' => "pages#test"
  match 'gallery' => "pages#candies"
  match 'contest' => "pages#contest"
  
  
  devise_scope :admin do
    get "admin/login", :to => "devise/sessions#new"
  end
  
  scope "/admin" do
    resources :venues
  end

  root :to => "pages#home"

end

app/models/candy.rb
class Candy < ActiveRecord::Base
  belongs_to :venue
  #has_and_belongs_to_many :users
  has_many :recommendations
  has_many :users, :through => :recommendations
  has_many :photos
  serialize :data
  accepts_nested_attributes_for :photos
  
  def after_initialize
    if self[:data]
      #self[:pic] = self[:data]['photo'] ? self[:data]['photo'].gsub('userpix_thumbs', 'userpix') : '#'
      
      #self[:pic] = self.photos.first ? self.photos.first.photo.url(:original) : self[:data]['photo'].gsub('userpix_thumbs', 'userpix')
#      if self[:is_candy]
#        has_photo = self[:default_photo]
#        
#        self[:thumbnail] = has_photo.nil? ? self[:data]['photo'] : self.photos.empty? ? 
#        self[:data]['photo'] : 
#        self.photos.find_by_id(has_photo) ? self.photos.find_by_id(has_photo).photo.url(:thumb) :
#        self.photos.first.photo.url(:thumb)
#        
#        self[:pic] = has_photo.nil? || self.photos.empty? ? self[:data]['photo'].gsub('userpix_thumbs', 'userpix') : 
#        self.photos.find_by_id(has_photo) ? self.photos.find_by_id(has_photo).photo.url(:original) :
#        self.photos.first.photo.url(:original)
#      else
#
#      end
#        self[:thumbnail] = self[:data]['photo']
#        self[:pic] = self[:data]['photo'].gsub('userpix_thumbs', 'userpix')
    end
    
    # Get the scout who discovered this candy
   # candy_scout = CandiesUser.find_by_candy_id(self.id)
#    self[:scout] = User.find_by_id(candy_scout.user_id) if !candy_scout.nil?
    #self[:scout] = self.users.first if !self.recommendations.empty?
    
    candy_keys = Candy.candy_status_list
    
    if self[:is_candy]
      self[:candy_status] = 
      case self[:score]
      when 0 then nil
      when 1..2 then candy_keys[1][:name]
      when 3..4 then candy_keys[2][:name]
      when 5..6 then candy_keys[3][:name]
      when 7..8 then candy_keys[4][:name]
      when 9..10 then candy_keys[5][:name]
      else candy_keys[6][:name]
      end
    else
      self[:candy_status] = self[:rejected] ? "Rejected" : "Pending"
    end
                
  end
  
  def get_pic(type)
    has_photo = self[:default_photo]
    
    if type == 'thumbnail'
      self[:thumbnail] = has_photo.nil? ? self[:data]['photo'] : self.photos.empty? ? 
      self[:data]['photo'] : 
      self.photos.find_by_id(has_photo) ? self.photos.find_by_id(has_photo).photo.url(:thumb) :
      self.photos.first.photo.url(:thumb)
      
      return self[:thumbnail]
    else
      self[:pic] = has_photo.nil? || self.photos.empty? ? self[:data]['photo'].gsub('userpix_thumbs', 'userpix') : 
      self.photos.find_by_id(has_photo) ? self.photos.find_by_id(has_photo).photo.url(:original) :
      self.photos.first.photo.url(:original)
      
      return self [:pic]
    end
    
  end
  
  def get_scout
    return self.users.where("recommended = true").first
  end
  
  def self.candy_status_list
    return [
    {:name=>"Pending",:count=>0},
    {:name=>"Sweetie",:count=>0}, 
    {:name=>"Rising Star",:count=>0}, 
    {:name=>"Starlet",:count=>0},
    {:name=>"Hot Candy",:count=>0},
    {:name=>"Beauty Queen",:count=>0},
    {:name=>"Super Candy Star",:count=>0},
    {:name=>"Rejected",:count=>0}]
  end
  
  def self.update_profile(candy, access_token)
    @@auth = Authentication.get_keys
    
    #access_token = User.find_by_email('wilson@spotcandy.com').authentications.where("provider = ?",'foursquare').first.access_token
    foursquare_candy = JSON.parse(Authentication.req('foursquare').request(
    :get, "https://api.foursquare.com/v2/users/#{candy.pid}",
    :client_id => @@auth[:key],
    :client_secret => @@auth[:secret],
    :oauth_token => access_token
    ))
      
    candy.data['photo'] = foursquare_candy['response']['user']['photo']
    candy.save
    
    refresh_photo = true
    
    # Save photos with paperclip for candy
    candy_photos = candy.photos
    
    if candy.is_candy && !candy_photos.empty?
      candy_current_photo = candy.data['photo'].gsub('userpix_thumbs', 'userpix')
      
      # New Foursquare Photo
      if candy.photos.find_by_photo_remote_url(candy_current_photo).nil?
      attr = {:default_photo => candy.photos.first.id, :photos_attributes => {candy.photos.count => {:photo_remote_url => candy_current_photo}}}
      candy.update_attributes(attr);
      refresh_photo = true
      else
      refresh_photo = false
      end
      
      
    end
    
    if refresh_photo
      pic = candy.data['photo'].gsub('userpix_thumbs', 'userpix')
      thumbnail = candy.data['photo']
    else
      pic = candy.get_pic('original')
      thumbnail = candy.get_pic('thumbnail')
    end
    
    return candy_photo = {:pic => pic, :thumbnail => thumbnail}
  end
  
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  layout 'application'
  
  def cleanup
    
    @list = []
    Candy.where("score = 0 AND flag_status = 0").order("created_at").limit(500).each do |c|
      diff = (Time.now.to_i - c.created_at.to_i)/(60*60*24)
      if diff >= 14
        c.flag_status = 2
        c.save
        @list << c.id
      end
    end
    
  end
  
  def privileges
    render :layout => 'mobile'
  end
  
  def profile
    @candy = Candy.find_by_pid(params[:pid])
    render :layout => 'mobile'
  end
  
  def display
    @candy = Candy.find(params[:id])
    render :layout => false
  end
  
  def grid
    #rand_id = rand(Candy.count)
    if params[:type] == 'nearby'
      @candies = Candy.where("is_candy = true").limit(15).order("created_at DESC").find_all_by_venue_id(session[:trending])
    end
    
    if params[:type] == 'recent'
      order = "created_at DESC"
      @candies = Candy.where("is_candy = true").order(order).limit(15)
    end
    
    if params[:type] == 'popular'
      order = "score DESC"
      @candies = Candy.where("is_candy = true AND score > 1").order(order)
      @candies = @candies.sort_by{rand}.slice(0,15)
    end
    
    if params[:type].nil?
      @candies = Candy.where("is_candy = true").order("RANDOM()").limit(15)
    end

    respond_to do |format|
      format.html { render :layout => false }
      format.json  { render :json => @candies }
    end
  end
  
  def detail
    authenticate_user!
    @candy = Candy.find(params[:id])
    respond_to do |format|
      format.html {render :layout => false}
      format.json  { render :json => @candy }
    end
  end
  
  def update_profile
    @candy = Candy.find(params[:id])
    
    @@auth = Authentication.get_keys
    
    refresh_photo = true
    
    #access_token = User.find_by_email('wilson@spotcandy.com').authentications.where("provider = ?",'foursquare').first.access_token
    foursquare_candy = JSON.parse(Authentication.req('foursquare').request(
    :get, "https://api.foursquare.com/v2/users/#{@candy.pid}",
    :client_id => @@auth[:key],
    :client_secret => @@auth[:secret],
    :oauth_token => session[:oauth]['foursquare']
    ))
      
    @candy.data['photo'] = foursquare_candy['response']['user']['photo']
    @candy.save

    # Save photos with paperclip for candy
    candy_photos = @candy.photos
    
    if @candy.is_candy && !candy_photos.empty?
      candy_current_photo = @candy.data['photo'].gsub('userpix_thumbs', 'userpix')
      
      # New Foursquare Photo
      if @candy.photos.find_by_photo_file_name(candy_current_photo[-20,20]).nil?
      attr = {:default_photo => @candy.photos.first.id, :photos_attributes => {@candy.photos.count => {:photo_remote_url => candy_current_photo}}}
      @candy.update_attributes(attr);
      refresh_photo = true
      else
      refresh_photo = false
      end

    end
    
    if refresh_photo
      pic = @candy.data['photo'].gsub('userpix_thumbs', 'userpix')
      thumbnail = @candy.data['photo']
    else
      pic = @candy.get_pic('original')
      thumbnail = @candy.get_pic('thumbnail')
    end
    
    respond_to do |format|
      format.json  { render :json => {:candy => @candy, :pic => pic, :thumbnail => thumbnail} }
    end
  end
  
  def flag
    @candy = Candy.find(params[:id])

    # Notified only if never flagged before
    if @candy.flag_status == 0
      if @candy.recommendations.where("recommended = ?", true).empty? || current_user.verified
        @candy.flag_status = 2
        @candy.save
      else
        flag_mail = UserMailer.flag_mail(@candy, current_user).deliver
      end
    else
      @candy = nil
    end
#    redirect_to({:controller => 'venues', :action => 'candies', :id => params[:venue_id], 
#    :anchor => "candy_#{params[:id]}"}, :notice => "We have been notified.")
    render :json => {:result => @candy}
#    respond_to do |format|
#      format.html # index.html.erb
#      format.json  { render :json => {:notified => @notified} }
#    end
  end
  
  # GET /candies
  # GET /candies.xml
  def index
    authenticate_admin!
    
    @candies = Candy.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @candies }
    end
  end

  # GET /candies/1
  # GET /candies/1.xml
  def show
    #authenticate_admin!
    #require 'open-uri'
    
    @candy = Candy.find(params[:id])
    @candy_photo = @candy.data['photo']
    @photo = @candy.photos.first
    
#    dir_pic = "#{RAILS_ROOT}/public/images/candies/#{@candy.id}"
#      
#    FileUtils.mkdir_p dir_pic if !File.directory?(dir_pic)
#    open(@candy_photo) do |o|
#      File.open("#{dir_pic}/#{@candy.pid}.jpg", "w") { |f| f << o.read }
#    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @candy }
      format.json  { render :json => @candy }
    end
  end

  # GET /candies/new
  # GET /candies/new.xml
  def new
    @candy = Candy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @candy }
    end
  end

  # GET /candies/1/edit
  def edit
    authenticate_admin!
    @candy = Candy.includes(:users, {:venue => :users}).find(params[:id])

    @watchers = @candy.venue.users.where("watched = true")
    
  end

  # POST /candies
  # POST /candies.xml
  def create
    @candy = Candy.new(params[:candy])

    respond_to do |format|
      if @candy.save
        format.html { redirect_to(@candy, :notice => 'Candy was successfully created.') }
        format.xml  { render :xml => @candy, :status => :created, :location => @candy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @candy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /candies/1
  # PUT /candies/1.xml
  def update
  
    @candy = Candy.includes(:users, {:venue => :users}).find(params[:id])
    
    if params[:send_mail] && params[:candy][:is_candy] == '1' && !@candy.is_candy
      @watchers = @candy.venue.users.where("watched = true")
      
      rand_id = rand(Candy.count)
      @watchers.each do |w|
        UserMailer.watch_new_candy_mail(w.email, @candy, rand_id).deliver if @candy.users.find_by_id(w.id).nil?
      end
      
    end
    
    if params[:candy][:facebook_update] == '1' && !@candy.facebook_update
    
      @facebook_page = Variable.find_by_name('facebook')
      
      if @facebook_page
        auth = Authentication.get_keys('facebook')
      
        @facebook_obj = JSON.parse(Authentication.req('facebook').request(
        :post, "https://graph.facebook.com/spotcandy/feed",
        :message => "Candy of the day spotted @\n#{@candy.venue.name}, #{@candy.venue.location['state']}",
        :picture => @candy.get_pic('thumbnail'),
        :name => "Candy of the Day",
        :description => "The world's most attractive people.",
        :link => "http://spotcandy.com/venue/#{@candy.venue.id}/candies",
        :caption => "http://m.spotcandy.com",
        :client_id => auth[:key],
        :client_secret => auth[:secret],
        :oauth_token => @facebook_page[:value]))
      end
      
    end
    
    @candy.update_attributes(params[:candy])
    
    if params[:candy][:flag_status] == '2' || params[:candy][:rejected] == '1'
      @candy.photos.destroy_all if !@candy.photos.empty?
      
#      params[:candy]['data'] = @candy.data
#      params[:candy]['data']['photo'] = @foursquare_candy['response']['user']['photo']
    end
    
    # Save photo with paperclip
#    photo = @candy.photos.first
#    
#    if photo
#      photo.photo_remote_url = @foursquare_candy['response']['user']['photo']
#      photo.save
#    else
#      params[:candy]['photos_attributes'] = {0 => {:photo_remote_url => @foursquare_candy['response']['user']['photo']}}
#      @candy.update_attributes(params[:candy])
#    end
    
    
    
    redirect_to(@candy, :notice => 'Candy was successfully updated.')
    
#    respond_to do |format|
#      if @candy.update_attributes(params[:candy])
##        format.html { redirect_to(@candy, :notice => 'Candy was successfully updated.') }
##        format.xml  { head :ok }
#        format.html { render :action => "edit" }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @candy.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.xml
  def destroy
    @candy = Candy.find(params[:id])
    @candy.destroy

    respond_to do |format|
      format.html { redirect_to(candies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/views/candies/_form.html.erb
No. of watchers: <%= @watchers.count %>
<ol>
<% @watchers.each do |w| %>
<li><%= w.email %></li>
<% end %>
</ol>


<%= form_for(@candy, :html => { :multipart => true}) do |f| %>
  <% if @candy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candy.errors.count, "error") %> prohibited this candy from being saved:</h2>
      <ul>
      <% @candy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br />
    <%= f.text_field :pid %>
  </div>
  
  <div class="field">
    <%= f.label :venue %><br />
    <%= @candy.venue.name %>
  </div>
  
  <% if !@candy.users.empty? %>
  <div class="field">
    <%= f.label :scout %><br />
    <%= @candy.users.first.email %>
  </div>
  <% end %>
  <div class="field">
  <%= f.label :Photo %><br />
  <a href="<%= @candy.get_pic('pic') %>" target="_blank">
  <%= image_tag @candy.get_pic('thumbnail'), :class => 'admin_candy_photo' %>
  </a>
  <%= link_to "Update Photo", {:controller => 'candies', :action => 'update_profile', :id => @candy.id, :format => 'json'} %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    I'm a <strong><%= @candy.data['gender'] %></strong>
  </div>
  
  <div class="field">
      <ul>
      <% @candy.photos.each do |photo| %>
        <% f.fields_for :photos, photo do |photo_fields| %>
          <li>
          <%= link_to (image_tag photo.photo.url(:thumb)), photo.photo.url(:original), :target => '_blank' %>
          <%= link_to 'Remove', {:controller => 'photos', :action => 'destroy', :id => photo.id}, :confirm => 'Are you sure?', :method => :delete %>
          </li>
        <% end %>
      <% end %>
      </ul>
  </div>
  
  <div class="field">
    <%= f.label :default_photo %><br />
    <%= f.text_field :default_photo %>
  </div>
  
  <div class="field">
    <%= f.label :flag_status %><br />
            <%= select(:candy, :flag_status, options_for_select([['None', 0], ['Pending', 1], ['Flagged', 2]], @candy.flag_status)) %>
  </div>
  
  <div class="field">
    <%= f.label :reject %><br />
    <%= f.check_box :rejected %>
  </div>
  
  <div class="field">
    <%= f.label :is_candy %><br />
    <%= f.check_box :is_candy %>
  </div>
  
  <div class="field">
    <%= f.label 'Post to Facebook' %><br />
    <%= f.check_box :facebook_update %>
  </div>
  
  <div class="field">
    <%= f.label :send_mail %><br />
    <%= check_box_tag 'send_mail', 1, true %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candies/cleanup.html.erb
<%= debug(@list) %>

app/views/candies/detail.html.erb
<%= image_tag @candy.pic, :class => 'original' %>
<% if @candy.photos.count > 1 %>
<script>
$(function() {
  $('#candy_photos li img').click(function(e){
    var thumb = $(this).attr('src');
    var original = thumb.replace("thumb", "original");
    $('img.original').attr('src', original);
  });
});
</script>
<hr>
<ul id="candy_photos">
<% @candy.photos.each do |photo| %>
<li><%= image_tag photo.photo.url(:thumb) %></li>
<% end %>
</ul>
<% end %>

app/views/candies/display.html.erb
<%= image_tag @candy.get_pic('original') %>
<div class="spotted">Spotted @ <%= link_to "#{@candy.venue.name}, #{@candy.venue.location['state']}", {:controller => 'venues', :action => 'candies', :id => @candy.venue_id} %> <br /><%= "#{time_ago_in_words(@candy.created_at)} ago" %>.
<%= link_to '', {:controller => 'candies', :action => 'update_profile', :id => @candy.id, :format => 'json'}, :class => 'nolink refresh_photo fr' %></div>

app/views/candies/edit.html.erb
<h1>Editing candy</h1>
<%= render 'form' %>

<%= link_to 'Show', @candy %> |
<%= link_to 'Back', candies_path %>

app/views/candies/grid.html.erb
<% if !@candies.empty? %>
<ul class="grid">
<% @candies.each do |c| %>
<li class="pic_loading<%= ' discovered' if current_user && !c.users.empty? && (c.users.first.id == current_user.id && c.is_candy) %>">
<%= link_to (image_tag c.get_pic('thumbnail'), :size => '91x91'), '#', :id => c.id, :class => 'nolink' %>
</li>
<% end %>
</ul>
<% else %>
<div align="left" style="padding:10px 0">There are no candies.</div>
<% end %>

app/views/candies/index.html.erb
<h1>Listing candies</h1>

<%= link_to 'New Candy', new_candy_path %>
<br />

<table>
  <tr>
    <th>Pid</th>
    <th>Is Candy</th>
    <th>Rejected</th>
    <th>Flag Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candies.each do |candy| %>
  <tr>
    <td><%= candy.pid %></td>
    <td><%= candy.is_candy %></td>
    <td><%= candy.rejected %></td>
    <td><%= candy.flag_status %></td>
    <td><%= link_to 'Show', candy %></td>
    <td><%= link_to 'Edit', edit_candy_path(candy) %></td>
    <td><%= link_to 'Destroy', candy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/candies/new.html.erb
<h1>New candy</h1>

<%= render 'form' %>

<%= link_to 'Back', candies_path %>

app/views/candies/privileges.html.erb
<h1>Candy Privileges</h1>
<p>Coming Soon!</p>

app/views/candies/profile.html.erb
<div align="center">
<% if @candy %>
<br />
<div class="pic s110 pic_loading"><%= image_tag @candy.get_pic('thumbnail') %></div>
<br />
<h1>Congratulations!</h1>
You are a candy and is recommended by <%= pluralize(@candy.users.count, 'user') %>!<br />
<u><%= link_to "Check out your privileges", candies_privileges_path %></u>.
<% else %>
<h1>Oops! You are not a candy yet!</h1>
<br />
<p>Get spotted by checking in to<br />
<%= link_to (image_tag 'foursquare-logo.png'), 'http://foursquare.com', :target => '_blank' %></p> 
<% end %>
<br /><br />
<% link_to "Vote for Candy Of The Month", contest_path %>
</div>

app/views/candies/show.html.erb
<p>
  <b>Pid:</b>
  <%= @candy.pid %>
</p>

<p>
  <b>Photo:</b>
  <a href="<%= @candy.get_pic('original') %>" target="_blank">
  <%= image_tag @candy.get_pic('thumbnail') %>
  </a>
</p>

<p>
  <b>Score:</b>
  <%= @candy.score %>
</p>


<%= link_to 'Edit', edit_candy_path(@candy) %> |
<%= link_to 'Back', candies_path %>

app/views/candies/update.html.erb
<%= debug(params) %>