config/routes.rb
Spotcandy::Application.routes.draw do
  resources :photos

  devise_for :admin

  resources :candies, :except => [:show]

  resources :venues, :except => [:show]
  

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  
  resources :users
  resources :admin, :only => [:index]
  
  get "candies/cleanup"
  get "candies/privileges"
  
  match 'auth/:provider' => 'authentications#index', :constraints => {:provider => /foursquare|facebook/}
  match 'auth/:provider/callback', :to => 'authentications#callback'
  match 'foursquare/connect' => 'authentications#connect'
  match 'search_candies' => "venues#search"
  match 'venue/:id/candies' => "venues#candies"
  match 'venue/people' => "venues#people"
  match 'venue/:id/add' => "venues#add"
  match 'venue/:id/watch' => "venues#watch"
  match 'venues/trending' => "venues#trending"
  match 'venues/popular' => "venues#popular"
  match 'venues/history' => "venues#history"
  match 'venues/random' => "venues#random"
  match 'candy/:id/add' => "users#add_candy"
  match 'candy/:id/remove' => "users#remove_candy"
  match 'candy/:id/flag' => "candies#flag"
  match 'candy/:id/update_profile' => "candies#update_profile"
  match 'candy/:id/photos' => "candies#detail"
  match 'candy/:id/display' => "candies#display"
  match 'candy/:pid/profile' => "candies#profile"
  match 'candies/cleanup' => "candies#cleanup"
  match 'candies/:id' => "candies#show"
  match 'candies-grid' => "candies#grid"
  match 'user/:id/candies' => "users#candies"
  match 'scout/:id/candies' => "users#candies_list"
  match 'leaderboard' => "pages#home"
  match 'faq' => "pages#faq"
  match 'spotted' => "pages#stream"
  match 'pages/test' => "pages#test"
  match 'gallery' => "pages#candies"
  match 'contest' => "pages#contest"
  
  
  devise_scope :admin do
    get "admin/login", :to => "devise/sessions#new"
  end
  
  scope "/admin" do
    resources :venues
  end

  root :to => "pages#home"

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :candy
  
  require 'open-uri'
  has_attached_file :photo, :styles => { :thumb => "110x110#" },
  :storage => :s3,
  :s3_credentials => "#{::Rails.root.to_s}/config/s3.yml",
  :path => "/:id/:style/:filename"
#  :path => ":rails_root/public/images/candies/:id/:style/:basename.:extension",
#  :url => "/images/candies/:id/:style/:basename.:extension"
  
  
  before_validation :download_remote_photo
  
  private

  def download_remote_photo
    self.photo = do_download_remote_photo
  end

  def do_download_remote_photo
    io = open(URI.parse(photo_remote_url))
    def io.original_filename; base_uri.path.split('/').last; end
    io.original_filename.blank? ? nil : io
  rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_admin!
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => { :multipart => true }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candy_id %><br />
    <%= f.text_field :candy_id %>
  </div>
  
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  
  <div class="field">
    <%= f.label :photo_remote_url %><br />
    <%= f.text_field :photo_remote_url %>
  </div>
  
  <!--
  <div class="field">
    <%= f.label :photo_file_name %><br />
    <%= f.text_field :photo_file_name %>
  </div>
  <div class="field">
    <%= f.label :photo_content_type %><br />
    <%= f.text_field :photo_content_type %>
  </div>
  <div class="field">
    <%= f.label :photo_file_size %><br />
    <%= f.text_field :photo_file_size %>
  </div>
  <div class="field">
    <%= f.label :photo_updated_at %><br />
    <%= f.datetime_select :photo_updated_at %>
  </div>
  -->
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Candy</th>
    <th>Photo file name</th>
    <th>Photo content type</th>
    <th>Photo file size</th>
    <th>Photo updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.candy_id %></td>
    <td><%= photo.photo_file_name %></td>
    <td><%= photo.photo_content_type %></td>
    <td><%= photo.photo_file_size %></td>
    <td><%= photo.photo_updated_at %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Candy:</b>
  <%= @photo.candy_id %>
</p>

<p>
  <b>Photo file name:</b>
  <%= @photo.photo_file_name %>
</p>

<p>
  <b>Photo content type:</b>
  <%= @photo.photo_content_type %>
</p>

<p>
  <b>Photo file size:</b>
  <%= @photo.photo_file_size %>
</p>

<p>
  <b>Photo updated at:</b>
  <%= @photo.photo_updated_at %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>