config/routes.rb
Spotcandy::Application.routes.draw do
  resources :photos

  devise_for :admin

  resources :candies, :except => [:show]

  resources :venues, :except => [:show]
  

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  
  resources :users
  resources :admin, :only => [:index]
  
  get "candies/cleanup"
  get "candies/privileges"
  
  match 'auth/:provider' => 'authentications#index', :constraints => {:provider => /foursquare|facebook/}
  match 'auth/:provider/callback', :to => 'authentications#callback'
  match 'foursquare/connect' => 'authentications#connect'
  match 'search_candies' => "venues#search"
  match 'venue/:id/candies' => "venues#candies"
  match 'venue/people' => "venues#people"
  match 'venue/:id/add' => "venues#add"
  match 'venue/:id/watch' => "venues#watch"
  match 'venues/trending' => "venues#trending"
  match 'venues/popular' => "venues#popular"
  match 'venues/history' => "venues#history"
  match 'venues/random' => "venues#random"
  match 'candy/:id/add' => "users#add_candy"
  match 'candy/:id/remove' => "users#remove_candy"
  match 'candy/:id/flag' => "candies#flag"
  match 'candy/:id/update_profile' => "candies#update_profile"
  match 'candy/:id/photos' => "candies#detail"
  match 'candy/:id/display' => "candies#display"
  match 'candy/:pid/profile' => "candies#profile"
  match 'candies/cleanup' => "candies#cleanup"
  match 'candies/:id' => "candies#show"
  match 'candies-grid' => "candies#grid"
  match 'user/:id/candies' => "users#candies"
  match 'scout/:id/candies' => "users#candies_list"
  match 'leaderboard' => "pages#home"
  match 'faq' => "pages#faq"
  match 'spotted' => "pages#stream"
  match 'pages/test' => "pages#test"
  match 'gallery' => "pages#candies"
  match 'contest' => "pages#contest"
  
  
  devise_scope :admin do
    get "admin/login", :to => "devise/sessions#new"
  end
  
  scope "/admin" do
    resources :venues
  end

  root :to => "pages#home"

end

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotcandy</title>
  <%= stylesheet_link_tag "scaffold", "admin" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
  <div id="primary_links">
    <ul>
    <% if current_admin %>
    <li><%= link_to "Admin Logout", destroy_admin_session_path %></li>
    <% end %>
    </ul>
    
  </div>
</div>

<% if notice %><p id="notice"><%= notice %></p><% end %>
<%= yield %>

<%= debug(params) %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotcandy</title>
  <%= stylesheet_link_tag :all, "style" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
  <div id="primary_links">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to "Login", user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path, :class => "signup_button round" %></li>
      <% end %>
    </ul>
    
  </div>
</div>

<% if notice %><p id="notice"><%= notice %></p><% end %>
<%= yield %>

<%= debug(params) %>
</body>
</html>

app/views/layouts/mobile.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">

<head>
  <title>Spotcandy - Mobile</title>

  <meta name="google-site-verification" content="A7cI8zwVCytRq4Qnkv8O5z5u-nY22SPYFbYCX85KIPc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="description" content="The world's most attractive people.">

  <%= stylesheet_link_tag "themes/base/jquery.ui.all", "mobile/1140", "style" %>
  <%= javascript_include_tag :defaults, "jquery-ui/js/jquery-ui-1.8.9.custom.min.js" %>
  <%= csrf_meta_tag %>
  <% if request.env['HTTP_HOST'] != 'spotcandy.com.localhost:3000' && (action_name == 'home' || action_name == 'faq') %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3542483-12']);
    <% if current_user %>
    _gaq.push(['_setCustomVar',1,'Scout','<%= current_user.email %>']);
    <% end %>
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <% end %>
</head>
<body<%= yield :body_class %>>
<div id="header">
  <div id="left_nav"><%= yield :left_nav %></div>
  <div id="right_nav"><%= yield :right_nav %></div>
  <% debug(session[:is_female]) %>
  <div id="primary_links">
    <ul>
      <% if session[:is_female].nil? %>
      <li class="first"><%= link_to "Home", root_path  %></li>
      <% end %>
      <li><% link_to "Contest", contest_path %></li>
      <% if current_user && controller_name != 'sessions' %>
        <% if session[:is_female].nil? %>
        <li><%= link_to "Search", search_candies_path %></li>
        <li><%= link_to "Jump!", {:controller => 'venues', :action => 'candies', :id => 'random'} %></li>
        <% else %>
        <li><%= link_to "Profile", {:controller => 'candies', :action => 'profile', :pid => session[:is_female]} %></li>
        <li><%= link_to "Logout", destroy_user_session_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to "Login", user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path, :class => "signup_button round" %></li>
      <% end %>
    </ul>
  </div>
  <div class="clear"></div>
</div>
<div class="container">

	<div class="row">
		<div class="twelvecol">


          <% if notice %><p id="notice"><%= notice %></p><% end %>
          <%= yield %>
		</div>

	</div>
    
</div>
<%= yield :home_bottom %>

</body>
</html>

app/views/layouts/mobile_home.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <title>Spotcandy - Mobile</title>
  <meta name="google-site-verification" content="A7cI8zwVCytRq4Qnkv8O5z5u-nY22SPYFbYCX85KIPc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="description" content="The world's most attractive people.">
  
  <%= stylesheet_link_tag "themes/base/jquery.ui.all", "mobile/1140", "style" %>
  <%= javascript_include_tag :defaults, "jquery-ui/js/jquery-ui-1.8.9.custom.min.js" %>
  <%= csrf_meta_tag %>
  <script>
  $(function() {  
    $('#info_icon a').toggle(function() {
      $('body').addClass('about');
      $('.home_view').hide();
      $('.container').show();
      $(this).children('img').attr('src', '/images/close.png');
    }, function() {
      $('body').removeClass('about');
      $('.home_view').show();
      $('.container').hide();
      $(this).children('img').attr('src','/images/info.png');
    });  });
  </script>
  <% if request.env['HTTP_HOST'] != 'spotcandy.com.localhost:3000' %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3542483-12']);
    _gaq.push(['_trackPageview']);
 ]); 

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <% end %>
</head>
<body style="padding-bottom:10px">
<div id="header">
  <div id="left_nav"><%= yield :left_nav %></div>
  <div id="right_nav"><%= yield :right_nav %></div>
  <div id="primary_links" style="float:none;">
  <div align="center" id="logo">
  <%= link_to (image_tag "logo_spotcandy.png"), root_url %>
  <div id="info_icon" class="fr"><a href="#"><%= image_tag "info.png", :style => 'border:none' %></a></div></div>
  
  </div>
  <div class="clear"></div>
</div>

<% if notice %>
<div align="center" class="home_view">
<p id="notice" style="width:80%"><%= notice %></p>
<p>Meanwhile, you can check out our <br /><%= link_to "Facebook page", "http://www.facebook.com/pages/Spotcandy/141205252611125", :target => '_blank' %> or <br />
<%= link_to "follow us on Twitter", 'http://twitter.com/getspotcandy', :target => '_blank' %>.<br />Otherwise you can <%= link_to "login", '/auth/foursquare' %> again.</p>
</div>

<% else %>

<div id="home_candy_stream" class="home_view">
<%= yield %>
</div>

<% end %>

<div class="container" style="display:none;">

	<div class="row">
		<div class="twelvecol">
        <div align="center">
          <br />
          Welcome to Spotcandy - an ambitious project to identify the most attractive people(candies) in the world. <br />Get involved today.
          <br />
          <hr style="border-bottom:1px solid #F56EB6; border-top:1px solid #BF2879; border-width:1px 0 1px 0;">
          <%# link_to "Become a Candy Scout", new_user_registration_path, :style => 'color:#fff;text-shadow: #000 2px 2px 0;' %>
          <br />
          or
          <br />
          <%= link_to "Login", user_session_path, :style => 'color:#fff;text-shadow: #000 2px 2px 0;' %><br />
          if you already have an account.
          </div>
		</div>

	</div>
</div>


</body>
</html>